nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: ['Content-Type']
        allow_methods: ['DELETE']
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: '*'
    paths:
        "^/api":
            allow_origin: [ '*' ]
            allow_headers: [ '*' ,'Content-Type', 'Accept']
            allow_methods: [ 'POST', 'PUT', 'PATCH', 'GET', 'DELETE' ]
            max_age: 3600

