#index:
#    path: /
#    controller: App\Controller\Rest\ArticlesController::indexAction

#articles:
#    type:     rest
#    host:     ANY
#    resource: App\Controller\Rest\ArticlesController

#blog_home:
#    path:     /
#    defaults: { _controller: SensioBlogBundle:Post:index }

logout:
    path: /articles/logout